apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- janua-admin.yaml
- janua-api.yaml
- janua-dashboard.yaml
- janua-docs.yaml
- janua-website.yaml
images:
- digest: sha256:072378adaa5d1a96864de3c9923f438b964796ee8ac42adf0af70438998e4073
  name: ghcr.io/madfam-org/janua-admin
  newName: ghcr.io/madfam-org/janua-admin
- digest: sha256:551399e3c69702716a3919c5cf93b3216b05360a7fbcbcd0f72b3a4e20a5db1c
  name: ghcr.io/madfam-org/janua-api
  newName: ghcr.io/madfam-org/janua-api
- digest: sha256:6a820edd43c00caf10764a5c44719e8dc97286db8eeb77d80f9aff29fa0b341e
  name: ghcr.io/madfam-org/janua-dashboard
  newName: ghcr.io/madfam-org/janua-dashboard
- digest: sha256:e8eb71ae4ae46a8fbccccf6ea4c7b4266008005eb067bd2fa14d981bd9cb88fd
  name: ghcr.io/madfam-org/janua-docs
  newName: ghcr.io/madfam-org/janua-docs
- digest: sha256:27db668ac6c2fca8415a076542ff3ae9b9a8337dc42707af4b76b1d6d9dfefad
  name: ghcr.io/madfam-org/janua-website
  newName: ghcr.io/madfam-org/janua-website
