apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- janua-admin.yaml
- janua-api.yaml
- janua-dashboard.yaml
- janua-docs.yaml
- janua-website.yaml
images:
- digest: sha256:57b04a74e789f952e533c3c1627fcf68fbaadab4a0a44aa8c647cdf3ef56230f
  name: ghcr.io/madfam-org/janua-admin
  newName: ghcr.io/madfam-org/janua-admin
- digest: sha256:4d6939475d3d50bb2ecf53b4459447ca1860519b5f0bef4b886d10afee69b9cf
  name: ghcr.io/madfam-org/janua-api
  newName: ghcr.io/madfam-org/janua-api
- digest: sha256:036030ec8c977bb725e9e879469d61a7ef87851633874b9a608ee31085f86f13
  name: ghcr.io/madfam-org/janua-dashboard
  newName: ghcr.io/madfam-org/janua-dashboard
- digest: sha256:e8eb71ae4ae46a8fbccccf6ea4c7b4266008005eb067bd2fa14d981bd9cb88fd
  name: ghcr.io/madfam-org/janua-docs
  newName: ghcr.io/madfam-org/janua-docs
- digest: sha256:3edab9c194af0664216ed67ea0476fde6beebade0170d9401c1f329d73d7e08a
  name: ghcr.io/madfam-org/janua-website
  newName: ghcr.io/madfam-org/janua-website
