"""Genesis schema - complete Janua database (flattened)

Revision ID: 000
Revises: None
Create Date: 2025-12-09

This is the baseline migration for Janua. All tables are created from scratch.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '000'  # noqa: F841 - Required by Alembic
down_revision: Union[str, None] = None  # noqa: F841 - Required by Alembic
branch_labels: Union[str, Sequence[str], None] = None  # noqa: F841 - Required by Alembic
depends_on: Union[str, Sequence[str], None] = None  # noqa: F841 - Required by Alembic


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locales',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('native_name', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_rtl', sa.Boolean(), nullable=True),
    sa.Column('translation_progress', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locales_code'), 'locales', ['code'], unique=True)
    op.create_table('migration_templates',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.Enum('AUTH0', 'OKTA', 'FIREBASE', 'COGNITO', 'CUSTOM', name='migrationprovider'), nullable=True),
    sa.Column('config_schema', postgresql.JSONB(), nullable=True),
    sa.Column('mapping_rules', postgresql.JSONB(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plans',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_monthly', sa.Integer(), nullable=True),
    sa.Column('price_yearly', sa.Integer(), nullable=True),
    sa.Column('features', postgresql.JSONB(), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('max_organizations', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('translation_keys',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('default_value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translation_keys_key'), 'translation_keys', ['key'], unique=True)
    op.create_table('users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', 'PENDING', 'DELETED', name='userstatus'), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('profile_image_url', sa.String(length=500), nullable=True),
    sa.Column('user_metadata', postgresql.JSONB(), nullable=True),
    sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('last_sign_in_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=True),
    sa.Column('mfa_secret', sa.String(length=255), nullable=True),
    sa.Column('mfa_backup_codes', postgresql.JSONB(), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('phone_verified', sa.Boolean(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('activity_logs',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=255), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('activity_metadata', postgresql.JSONB(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('details', postgresql.JSONB(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_verifications',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('magic_links',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('redirect_url', sa.String(length=500), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('oauth_accounts',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('provider', sa.Enum('GOOGLE', 'GITHUB', 'MICROSOFT', 'APPLE', 'DISCORD', 'TWITTER', 'LINKEDIN', 'SLACK', name='oauthprovider'), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('provider_email', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('provider_data', postgresql.JSONB(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('subscription_tier', sa.String(length=100), nullable=True),
    sa.Column('owner_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('billing_plan', sa.String(length=100), nullable=True),
    sa.Column('billing_email', sa.String(length=255), nullable=True),
    sa.Column('billing_customer_id', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('settings', postgresql.JSONB(), nullable=True),
    sa.Column('org_metadata', postgresql.JSONB(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_billing_customer_id'), 'organizations', ['billing_customer_id'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('passkeys',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('credential_id', sa.String(length=500), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('sign_count', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('authenticator_attachment', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('credential_id')
    )
    op.create_table('password_resets',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('privacy_settings',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('email_marketing', sa.Boolean(), nullable=True),
    sa.Column('email_product_updates', sa.Boolean(), nullable=True),
    sa.Column('email_security_alerts', sa.Boolean(), nullable=True),
    sa.Column('sms_marketing', sa.Boolean(), nullable=True),
    sa.Column('phone_marketing', sa.Boolean(), nullable=True),
    sa.Column('analytics_tracking', sa.Boolean(), nullable=True),
    sa.Column('personalization', sa.Boolean(), nullable=True),
    sa.Column('third_party_sharing', sa.Boolean(), nullable=True),
    sa.Column('profiling', sa.Boolean(), nullable=True),
    sa.Column('automated_decision_making', sa.Boolean(), nullable=True),
    sa.Column('essential_cookies', sa.Boolean(), nullable=True),
    sa.Column('functional_cookies', sa.Boolean(), nullable=True),
    sa.Column('analytics_cookies', sa.Boolean(), nullable=True),
    sa.Column('marketing_cookies', sa.Boolean(), nullable=True),
    sa.Column('profile_visibility', sa.String(length=50), nullable=True),
    sa.Column('data_export_format', sa.String(length=50), nullable=True),
    sa.Column('deletion_preference', sa.String(length=100), nullable=True),
    sa.Column('data_residency_preference', sa.String(length=100), nullable=True),
    sa.Column('cross_border_transfer_consent', sa.Boolean(), nullable=True),
    sa.Column('gdpr_explicit_consent', sa.Boolean(), nullable=True),
    sa.Column('ccpa_opt_out', sa.Boolean(), nullable=True),
    sa.Column('last_updated_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('privacy_policy_version', sa.String(length=50), nullable=True),
    sa.Column('consent_renewal_due', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['last_updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_privacy_settings_tenant_id'), 'privacy_settings', ['tenant_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('access_token_jti', sa.String(length=255), nullable=True),
    sa.Column('refresh_token_jti', sa.String(length=255), nullable=True),
    sa.Column('refresh_token_family', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_reason', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('access_token_jti'),
    sa.UniqueConstraint('refresh_token'),
    sa.UniqueConstraint('refresh_token_jti'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_sessions_refresh_token_family'), 'sessions', ['refresh_token_family'], unique=False)
    op.create_table('token_claims',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('claims', postgresql.JSONB(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token_pairs',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('translations',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('translation_key_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('locale_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('approved_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['locale_id'], ['locales.id'], ),
    sa.ForeignKeyConstraint(['translation_key_id'], ['translation_keys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_keys',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=False),
    sa.Column('scopes', postgresql.JSONB(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checkout_sessions',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('price_id', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('session_metadata', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('compliance_controls',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('control_id', sa.String(length=100), nullable=False),
    sa.Column('control_name', sa.String(length=255), nullable=False),
    sa.Column('compliance_framework', sa.Enum('GDPR', 'SOC2', 'HIPAA', 'CCPA', 'PCI_DSS', 'ISO_27001', name='complianceframework'), nullable=False),
    sa.Column('control_family', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('control_objective', sa.Text(), nullable=True),
    sa.Column('control_activity', sa.Text(), nullable=True),
    sa.Column('control_type', sa.String(length=50), nullable=True),
    sa.Column('control_frequency', sa.String(length=50), nullable=True),
    sa.Column('implementation_status', sa.String(length=50), nullable=True),
    sa.Column('implementation_date', sa.DateTime(), nullable=True),
    sa.Column('implementation_evidence', postgresql.JSONB(), nullable=True),
    sa.Column('responsible_party', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('last_tested_date', sa.DateTime(), nullable=True),
    sa.Column('test_frequency', sa.String(length=50), nullable=True),
    sa.Column('test_results', postgresql.JSONB(), nullable=True),
    sa.Column('effectiveness_rating', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('COMPLIANT', 'NON_COMPLIANT', 'EFFECTIVE', 'INEFFECTIVE', 'NEEDS_IMPROVEMENT', 'NOT_TESTED', 'EXCEPTION', name='controlstatus'), nullable=False),
    sa.Column('last_assessed', sa.DateTime(), nullable=True),
    sa.Column('assessed_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('deficiencies_identified', postgresql.JSONB(), nullable=True),
    sa.Column('remediation_plan', sa.Text(), nullable=True),
    sa.Column('remediation_due_date', sa.DateTime(), nullable=True),
    sa.Column('remediation_status', sa.String(length=50), nullable=True),
    sa.Column('evidence_location', sa.String(length=500), nullable=True),
    sa.Column('evidence_retention_period', sa.Integer(), nullable=True),
    sa.Column('documentation_url', sa.String(length=500), nullable=True),
    sa.Column('inherent_risk_rating', sa.String(length=50), nullable=True),
    sa.Column('residual_risk_rating', sa.String(length=50), nullable=True),
    sa.Column('risk_tolerance', sa.String(length=50), nullable=True),
    sa.Column('compensating_controls', postgresql.JSONB(), nullable=True),
    sa.Column('monitoring_method', sa.String(length=100), nullable=True),
    sa.Column('monitoring_frequency', sa.String(length=50), nullable=True),
    sa.Column('key_metrics', postgresql.JSONB(), nullable=True),
    sa.Column('alerting_enabled', sa.Boolean(), nullable=True),
    sa.Column('last_reviewed_date', sa.DateTime(), nullable=True),
    sa.Column('review_frequency', sa.String(length=50), nullable=True),
    sa.Column('reviewer_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('audit_findings', postgresql.JSONB(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['responsible_party'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_controls_tenant_id'), 'compliance_controls', ['tenant_id'], unique=False)
    op.create_table('compliance_logs',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('compliance_type', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=255), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('details', postgresql.JSONB(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_reports',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('report_id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('report_type', sa.String(length=100), nullable=False),
    sa.Column('compliance_framework', sa.Enum('GDPR', 'SOC2', 'HIPAA', 'CCPA', 'PCI_DSS', 'ISO_27001', name='complianceframework'), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('findings', postgresql.JSONB(), nullable=True),
    sa.Column('recommendations', postgresql.JSONB(), nullable=True),
    sa.Column('risk_assessment', postgresql.JSONB(), nullable=True),
    sa.Column('compliance_score', sa.Integer(), nullable=True),
    sa.Column('metrics', postgresql.JSONB(), nullable=True),
    sa.Column('kpis', postgresql.JSONB(), nullable=True),
    sa.Column('trends', postgresql.JSONB(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('reviewed_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('approved_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('recipients', postgresql.JSONB(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('publication_url', sa.String(length=500), nullable=True),
    sa.Column('confidentiality_level', sa.String(length=50), nullable=True),
    sa.Column('generated_by', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('generation_method', sa.String(length=100), nullable=True),
    sa.Column('data_sources', postgresql.JSONB(), nullable=True),
    sa.Column('action_items', postgresql.JSONB(), nullable=True),
    sa.Column('follow_up_required', sa.Boolean(), nullable=True),
    sa.Column('next_review_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id')
    )
    op.create_index(op.f('ix_compliance_reports_tenant_id'), 'compliance_reports', ['tenant_id'], unique=False)
    op.create_table('consent_records',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('consent_type', sa.Enum('MARKETING', 'ANALYTICS', 'FUNCTIONAL', 'NECESSARY', 'PERSONALIZATION', 'THIRD_PARTY', 'COOKIES', 'PROFILING', name='consenttype'), nullable=False),
    sa.Column('purpose', sa.String(length=500), nullable=False),
    sa.Column('legal_basis', sa.Enum('CONSENT', 'CONTRACT', 'LEGAL_OBLIGATION', 'VITAL_INTERESTS', 'PUBLIC_TASK', 'LEGITIMATE_INTERESTS', name='legalbasis'), nullable=True),
    sa.Column('status', sa.Enum('GIVEN', 'WITHDRAWN', 'EXPIRED', 'PENDING', name='consentstatus'), nullable=True),
    sa.Column('given_at', sa.DateTime(), nullable=False),
    sa.Column('withdrawn_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('consent_method', sa.String(length=100), nullable=True),
    sa.Column('consent_version', sa.String(length=50), nullable=True),
    sa.Column('data_categories', postgresql.JSONB(), nullable=True),
    sa.Column('processing_purposes', postgresql.JSONB(), nullable=True),
    sa.Column('third_parties', postgresql.JSONB(), nullable=True),
    sa.Column('retention_period', sa.Integer(), nullable=True),
    sa.Column('consent_evidence', postgresql.JSONB(), nullable=True),
    sa.Column('withdrawal_reason', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_records_tenant_id'), 'consent_records', ['tenant_id'], unique=False)
    op.create_table('custom_domains',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('ssl_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('data_breach_incidents',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('breach_id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('breach_type', sa.String(length=100), nullable=False),
    sa.Column('affected_records_count', sa.Integer(), nullable=True),
    sa.Column('data_categories_affected', postgresql.JSONB(), nullable=True),
    sa.Column('affected_users', postgresql.JSONB(), nullable=True),
    sa.Column('geographic_scope', postgresql.JSONB(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=True),
    sa.Column('contained_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('authority_notification_required', sa.Boolean(), nullable=True),
    sa.Column('authority_notified_at', sa.DateTime(), nullable=True),
    sa.Column('authority_notification_reference', sa.String(length=255), nullable=True),
    sa.Column('user_notification_required', sa.Boolean(), nullable=True),
    sa.Column('users_notified_at', sa.DateTime(), nullable=True),
    sa.Column('notification_method', sa.String(length=100), nullable=True),
    sa.Column('notification_deadline', sa.DateTime(), nullable=True),
    sa.Column('deadline_met', sa.Boolean(), nullable=True),
    sa.Column('deadline_miss_reason', sa.Text(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('technical_measures_taken', sa.Text(), nullable=True),
    sa.Column('organizational_measures_taken', sa.Text(), nullable=True),
    sa.Column('lessons_learned', sa.Text(), nullable=True),
    sa.Column('likelihood_of_risk', sa.String(length=50), nullable=True),
    sa.Column('risk_mitigation_measures', sa.Text(), nullable=True),
    sa.Column('ongoing_monitoring_required', sa.Boolean(), nullable=True),
    sa.Column('gdpr_applicable', sa.Boolean(), nullable=True),
    sa.Column('hipaa_applicable', sa.Boolean(), nullable=True),
    sa.Column('ccpa_applicable', sa.Boolean(), nullable=True),
    sa.Column('incident_commander_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('legal_team_involved', sa.Boolean(), nullable=True),
    sa.Column('external_counsel_involved', sa.Boolean(), nullable=True),
    sa.Column('law_enforcement_involved', sa.Boolean(), nullable=True),
    sa.Column('forensic_report_url', sa.String(length=500), nullable=True),
    sa.Column('legal_analysis_url', sa.String(length=500), nullable=True),
    sa.Column('communication_template_used', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('resolution_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['incident_commander_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('breach_id')
    )
    op.create_index(op.f('ix_data_breach_incidents_tenant_id'), 'data_breach_incidents', ['tenant_id'], unique=False)
    op.create_table('data_retention_policies',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('compliance_framework', sa.Enum('GDPR', 'SOC2', 'HIPAA', 'CCPA', 'PCI_DSS', 'ISO_27001', name='complianceframework'), nullable=True),
    sa.Column('data_category', sa.Enum('IDENTITY', 'CONTACT', 'DEMOGRAPHIC', 'FINANCIAL', 'TECHNICAL', 'BEHAVIORAL', 'HEALTH', 'BIOMETRIC', 'LOCATION', 'SOCIAL', 'PROFESSIONAL', 'EDUCATIONAL', name='datacategory'), nullable=False),
    sa.Column('data_source', sa.String(length=255), nullable=True),
    sa.Column('legal_basis', sa.Enum('CONSENT', 'CONTRACT', 'LEGAL_OBLIGATION', 'VITAL_INTERESTS', 'PUBLIC_TASK', 'LEGITIMATE_INTERESTS', name='legalbasis'), nullable=True),
    sa.Column('retention_period_days', sa.Integer(), nullable=False),
    sa.Column('deletion_method', sa.String(length=100), nullable=True),
    sa.Column('archival_required', sa.Boolean(), nullable=True),
    sa.Column('archival_period_days', sa.Integer(), nullable=True),
    sa.Column('auto_deletion_enabled', sa.Boolean(), nullable=True),
    sa.Column('notification_before_deletion_days', sa.Integer(), nullable=True),
    sa.Column('require_approval', sa.Boolean(), nullable=True),
    sa.Column('policy_version', sa.String(length=50), nullable=True),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('review_date', sa.DateTime(), nullable=True),
    sa.Column('approved_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_retention_policies_tenant_id'), 'data_retention_policies', ['tenant_id'], unique=False)
    op.create_table('data_subject_requests',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tenant_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('request_type', sa.Enum('ACCESS', 'RECTIFICATION', 'ERASURE', 'PORTABILITY', 'RESTRICTION', 'OBJECTION', name='datasubjectrequesttype'), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'ACKNOWLEDGED', 'IN_PROGRESS', 'COMPLETED', 'REJECTED', 'EXPIRED', 'FAILED', name='requeststatus'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data_categories', postgresql.JSONB(), nullable=True),
    sa.Column('date_range_start', sa.DateTime(), nullable=True),
    sa.Column('date_range_end', sa.DateTime(), nullable=True),
    sa.Column('specific_fields', postgresql.JSONB(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('response_due_date', sa.DateTime(), nullable=True),
    sa.Column('identity_verified', sa.Boolean(), nullable=True),
    sa.Column('identity_verification_method', sa.String(length=100), nullable=True),
    sa.Column('identity_verification_notes', sa.Text(), nullable=True),
    sa.Column('response_method', sa.String(length=100), nullable=True),
    sa.Column('response_data_url', sa.String(length=500), nullable=True),
    sa.Column('response_notes', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('legal_review_required', sa.Boolean(), nullable=True),
    sa.Column('legal_review_completed', sa.Boolean(), nullable=True),
    sa.Column('legal_reviewer_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_source', sa.String(length=100), nullable=True),
    sa.Column('assigned_to', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('processing_notes', sa.Text(), nullable=True),
    sa.Column('escalation_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['legal_reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_index(op.f('ix_data_subject_requests_tenant_id'), 'data_subject_requests', ['tenant_id'], unique=False)
    op.create_table('email_templates',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('template_type', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('variables', postgresql.JSONB(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enterprise_audit_logs',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('event_type', sa.Enum('USER_LOGIN', 'USER_LOGOUT', 'USER_CREATED', 'USER_UPDATED', 'USER_DELETED', 'ORGANIZATION_CREATED', 'ORGANIZATION_UPDATED', 'ORGANIZATION_DELETED', 'PERMISSION_GRANTED', 'PERMISSION_REVOKED', 'POLICY_CREATED', 'POLICY_UPDATED', 'POLICY_DELETED', 'SECURITY_ALERT', 'DATA_EXPORT', 'SYSTEM_CONFIG_CHANGED', name='auditeventtype'), nullable=False),
    sa.Column('resource_type', sa.String(length=255), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('event_data', postgresql.JSONB(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enterprise_features',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('feature_name', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('configuration', postgresql.JSONB(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invitations',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('migration_jobs',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('provider', sa.Enum('AUTH0', 'OKTA', 'FIREBASE', 'COGNITO', 'CUSTOM', name='migrationprovider'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', name='migrationstatus'), nullable=True),
    sa.Column('config', postgresql.JSONB(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('data', postgresql.JSONB(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oauth_clients',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('client_id', sa.String(length=255), nullable=False),
    sa.Column('client_secret_hash', sa.String(length=255), nullable=False),
    sa.Column('client_secret_prefix', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('redirect_uris', postgresql.JSONB(), nullable=True),
    sa.Column('allowed_scopes', postgresql.JSONB(), nullable=True),
    sa.Column('grant_types', postgresql.JSONB(), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_confidential', sa.Boolean(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_clients_client_id'), 'oauth_clients', ['client_id'], unique=True)
    op.create_table('organization_custom_roles',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('permissions', postgresql.JSONB(), nullable=True),
    sa.Column('parent_role_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['parent_role_id'], ['organization_custom_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization_invitations',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('organization_members',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization_settings',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('settings_data', postgresql.JSONB(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permission_definitions',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('resource_type', sa.String(length=255), nullable=False),
    sa.Column('actions', postgresql.JSONB(), nullable=True),
    sa.Column('conditions', postgresql.JSONB(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissions',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('resource', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('conditions', postgresql.JSONB(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policies',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rules', postgresql.JSONB(), nullable=True),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permissions', postgresql.JSONB(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scim_configurations',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('bearer_token', sa.String(length=500), nullable=True),
    sa.Column('configuration', postgresql.JSONB(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scim_resources',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('resource_type', sa.String(length=255), nullable=False),
    sa.Column('scim_id', sa.String(length=255), nullable=False),
    sa.Column('internal_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('attributes', postgresql.JSONB(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sso_configurations',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('provider', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('configuration', postgresql.JSONB(), nullable=True),
    sa.Column('metadata_url', sa.String(length=500), nullable=True),
    sa.Column('certificate', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('plan', sa.Enum('FREE', 'PRO', 'ENTERPRISE', name='billingplan'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CANCELED', 'PAST_DUE', 'UNPAID', 'TRIALING', name='subscriptionstatus'), nullable=False),
    sa.Column('billing_interval', sa.Enum('MONTHLY', 'YEARLY', name='billinginterval'), nullable=False),
    sa.Column('current_period_start', sa.DateTime(), nullable=False),
    sa.Column('current_period_end', sa.DateTime(), nullable=False),
    sa.Column('trial_end', sa.DateTime(), nullable=True),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('subscription_metadata', postgresql.JSONB(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_subscription_id')
    )
    op.create_table('webhook_endpoints',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('secret', sa.String(length=255), nullable=True),
    sa.Column('events', postgresql.JSONB(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webhook_events',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('data', postgresql.JSONB(), nullable=True),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webhooks',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('events', postgresql.JSONB(), nullable=True),
    sa.Column('secret', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('white_label_configurations',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('brand_name', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('favicon_url', sa.String(length=500), nullable=True),
    sa.Column('primary_color', sa.String(length=7), nullable=True),
    sa.Column('secondary_color', sa.String(length=7), nullable=True),
    sa.Column('custom_domain', sa.String(length=255), nullable=True),
    sa.Column('custom_domain_verified', sa.Boolean(), nullable=True),
    sa.Column('email_from_name', sa.String(length=255), nullable=True),
    sa.Column('email_from_address', sa.String(length=255), nullable=True),
    sa.Column('email_footer_text', sa.Text(), nullable=True),
    sa.Column('custom_css', sa.Text(), nullable=True),
    sa.Column('custom_javascript', sa.Text(), nullable=True),
    sa.Column('hide_powered_by', sa.Boolean(), nullable=True),
    sa.Column('features', postgresql.JSONB(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('custom_domain'),
    sa.UniqueConstraint('organization_id')
    )
    op.create_table('billing_usage',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('subscription_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('metric_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('subscription_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('invoice_number', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('stripe_invoice_id', sa.String(length=255), nullable=True),
    sa.Column('invoice_data', postgresql.JSONB(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number'),
    sa.UniqueConstraint('stripe_invoice_id')
    )
    op.create_table('migrated_users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('migration_job_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('janua_user_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', name='migrationstatus'), nullable=True),
    sa.Column('migration_metadata', postgresql.JSONB(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['janua_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['migration_job_id'], ['migration_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('migration_logs',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('migration_job_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['migration_job_id'], ['migration_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policy_evaluations',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('policy_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('subject_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('resource_type', sa.String(length=255), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=True),
    sa.Column('result', sa.Boolean(), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(), nullable=True),
    sa.Column('context', postgresql.JSONB(), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_evaluations_policy_id'), 'policy_evaluations', ['policy_id'], unique=False)
    op.create_index(op.f('ix_policy_evaluations_subject_id'), 'policy_evaluations', ['subject_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('role_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('permission_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_policies',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('role_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('policy_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_policies_policy_id'), 'role_policies', ['policy_id'], unique=False)
    op.create_index(op.f('ix_role_policies_role_id'), 'role_policies', ['role_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('role_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('scope', sa.String(length=50), nullable=True),
    sa.Column('granted_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_roles_organization_id'), 'user_roles', ['organization_id'], unique=False)
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('webhook_endpoint_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('webhook_event_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'DELIVERED', 'FAILED', 'RETRYING', name='webhookstatus'), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('last_attempt', sa.DateTime(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['webhook_endpoint_id'], ['webhook_endpoints.id'], ),
    sa.ForeignKeyConstraint(['webhook_event_id'], ['webhook_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('organization_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('invoice_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('payment_method', sa.String(length=100), nullable=True),
    sa.Column('stripe_payment_id', sa.String(length=255), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('payment_data', postgresql.JSONB(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_payment_id')
    )

    # === Migration 002 ===
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_failed_login', sa.DateTime(), nullable=True))

    # === Migration 003 ===
    op.add_column('sessions', sa.Column('device_fingerprint', sa.String(length=255), nullable=True))
    op.add_column('sessions', sa.Column('is_trusted_device', sa.Boolean(), nullable=True, server_default='false'))
    op.create_index(op.f('ix_sessions_device_fingerprint'), 'sessions', ['device_fingerprint'], unique=False)
    op.create_table('trusted_devices',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('device_fingerprint', sa.String(length=255), nullable=False),
        sa.Column('device_name', sa.String(length=255), nullable=True),
        sa.Column('user_agent', sa.Text(), nullable=True),
        sa.Column('ip_address', sa.String(length=50), nullable=True),
        sa.Column('last_ip_address', sa.String(length=50), nullable=True),
        sa.Column('last_location', sa.String(length=255), nullable=True),
        sa.Column('trust_expires_at', sa.DateTime(), nullable=True),
        sa.Column('last_used_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trusted_devices_user_id'), 'trusted_devices', ['user_id'], unique=False)
    op.create_index(op.f('ix_trusted_devices_device_fingerprint'), 'trusted_devices', ['device_fingerprint'], unique=False)
    op.create_unique_constraint(
        'uq_trusted_devices_user_device',
        'trusted_devices',
        ['user_id', 'device_fingerprint']
    )

    # === Migration 004 ===
    op.create_table('user_consents',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('client_id', sa.String(length=255), nullable=False),
        sa.Column('scopes', postgresql.JSONB(), nullable=False),
        sa.Column('granted_at', sa.DateTime(), nullable=True),
        sa.Column('expires_at', sa.DateTime(), nullable=True),
        sa.Column('revoked_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_consents_user_id'), 'user_consents', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_consents_client_id'), 'user_consents', ['client_id'], unique=False)
    op.create_unique_constraint(
        'uq_user_consents_user_client',
        'user_consents',
        ['user_id', 'client_id']
    )

    # === Migration 005 ===
    op.create_table('oauth_client_secrets',
        sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('client_id', postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column('secret_hash', sa.String(length=255), nullable=False),
        sa.Column('secret_prefix', sa.String(length=20), nullable=False),
        sa.Column('is_primary', sa.Boolean(), nullable=True, server_default='true'),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('expires_at', sa.DateTime(), nullable=True),
        sa.Column('revoked_at', sa.DateTime(), nullable=True),
        sa.Column('last_used_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column('revoked_by', postgresql.UUID(as_uuid=True), nullable=True),
        sa.ForeignKeyConstraint(['client_id'], ['oauth_clients.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['revoked_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_client_secrets_client_id'), 'oauth_client_secrets', ['client_id'], unique=False)
    op.create_index(op.f('ix_oauth_client_secrets_is_primary'), 'oauth_client_secrets', ['is_primary'], unique=False)

    # === Migration 006 ===
    op.add_column(
        "scim_configurations",
        sa.Column("provider", sa.String(50), nullable=True, server_default="custom"),
    )
    op.create_unique_constraint(
        "uq_scim_configurations_organization_id",
        "scim_configurations",
        ["organization_id"],
    )
    op.add_column(
        "scim_resources",
        sa.Column("external_id", sa.String(255), nullable=True),
    )
    op.add_column(
        "scim_resources",
        sa.Column("raw_attributes", postgresql.JSONB(astext_type=sa.Text()), nullable=True, server_default="{}"),
    )
    op.add_column(
        "scim_resources",
        sa.Column("sync_status", sa.String(50), nullable=True, server_default="pending"),
    )
    op.add_column(
        "scim_resources",
        sa.Column("last_synced_at", sa.DateTime(), nullable=True),
    )
    op.create_table(
        "scim_sync_logs",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("organization_id", postgresql.UUID(as_uuid=True), sa.ForeignKey("organizations.id"), nullable=False),
        sa.Column("operation", sa.String(50), nullable=False),  # create, update, delete, patch
        sa.Column("resource_type", sa.String(50), nullable=False),  # User, Group
        sa.Column("scim_id", sa.String(255), nullable=True),
        sa.Column("internal_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("status", sa.String(50), nullable=False),  # success, failed, partial
        sa.Column("request_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True, server_default="{}"),
        sa.Column("response_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True, server_default="{}"),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("error_code", sa.String(50), nullable=True),
        sa.Column("idp_request_id", sa.String(255), nullable=True),
        sa.Column("synced_at", sa.DateTime(), server_default=sa.func.now()),
        sa.Column("created_at", sa.DateTime(), server_default=sa.func.now()),
    )
    op.create_index(
        "ix_scim_sync_logs_organization_id",
        "scim_sync_logs",
        ["organization_id"],
    )
    op.create_index(
        "ix_scim_sync_logs_synced_at",
        "scim_sync_logs",
        ["synced_at"],
    )
    op.create_index(
        "ix_scim_sync_logs_status",
        "scim_sync_logs",
        ["status"],
    )
    op.create_index(
        "ix_scim_resources_sync_status",
        "scim_resources",
        ["sync_status"],
    )
    op.create_index(
        "ix_scim_resources_external_id",
        "scim_resources",
        ["external_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('webhook_deliveries')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_organization_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_role_policies_role_id'), table_name='role_policies')
    op.drop_index(op.f('ix_role_policies_policy_id'), table_name='role_policies')
    op.drop_table('role_policies')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_policy_evaluations_subject_id'), table_name='policy_evaluations')
    op.drop_index(op.f('ix_policy_evaluations_policy_id'), table_name='policy_evaluations')
    op.drop_table('policy_evaluations')
    op.drop_table('migration_logs')
    op.drop_table('migrated_users')
    op.drop_table('invoices')
    op.drop_table('billing_usage')
    op.drop_table('white_label_configurations')
    op.drop_table('webhooks')
    op.drop_table('webhook_events')
    op.drop_table('webhook_endpoints')
    op.drop_table('subscriptions')
    op.drop_table('sso_configurations')
    op.drop_table('scim_resources')
    op.drop_table('scim_configurations')
    op.drop_table('roles')
    op.drop_table('policies')
    op.drop_table('permissions')
    op.drop_table('permission_definitions')
    op.drop_table('organization_settings')
    op.drop_table('organization_members')
    op.drop_table('organization_invitations')
    op.drop_table('organization_custom_roles')
    op.drop_index(op.f('ix_oauth_clients_client_id'), table_name='oauth_clients')
    op.drop_table('oauth_clients')
    op.drop_table('notifications')
    op.drop_table('migration_jobs')
    op.drop_table('invitations')
    op.drop_table('enterprise_features')
    op.drop_table('enterprise_audit_logs')
    op.drop_table('email_templates')
    op.drop_index(op.f('ix_data_subject_requests_tenant_id'), table_name='data_subject_requests')
    op.drop_table('data_subject_requests')
    op.drop_index(op.f('ix_data_retention_policies_tenant_id'), table_name='data_retention_policies')
    op.drop_table('data_retention_policies')
    op.drop_index(op.f('ix_data_breach_incidents_tenant_id'), table_name='data_breach_incidents')
    op.drop_table('data_breach_incidents')
    op.drop_table('custom_domains')
    op.drop_index(op.f('ix_consent_records_tenant_id'), table_name='consent_records')
    op.drop_table('consent_records')
    op.drop_index(op.f('ix_compliance_reports_tenant_id'), table_name='compliance_reports')
    op.drop_table('compliance_reports')
    op.drop_table('compliance_logs')
    op.drop_index(op.f('ix_compliance_controls_tenant_id'), table_name='compliance_controls')
    op.drop_table('compliance_controls')
    op.drop_table('checkout_sessions')
    op.drop_table('api_keys')
    op.drop_table('translations')
    op.drop_table('token_pairs')
    op.drop_table('token_claims')
    op.drop_index(op.f('ix_sessions_refresh_token_family'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_privacy_settings_tenant_id'), table_name='privacy_settings')
    op.drop_table('privacy_settings')
    op.drop_table('password_resets')
    op.drop_table('passkeys')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_billing_customer_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_table('oauth_accounts')
    op.drop_table('magic_links')
    op.drop_table('email_verifications')
    op.drop_table('audit_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_translation_keys_key'), table_name='translation_keys')
    op.drop_table('translation_keys')
    op.drop_table('plans')
    op.drop_table('migration_templates')
    op.drop_index(op.f('ix_locales_code'), table_name='locales')
    op.drop_table('locales')
    # ### end Alembic commands ###